### ISSUE TITLE
[feat] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by hanseulhee** [GymHubCommunity/GymHub-FE#1]
## 🏋🏻 어떤 개발 사항인가요?

프로젝트 초기 세팅을 진행합니다

## 💪🏻 TODO

- [x]  라이센스 적용
- [x]  필요한 패키지 설치
- [x] 디렉토리 구조 설정
- [x] eslint
- [x] prettier
- [x]  issue, pr 템플릿
- [x]  auto assign
- [x]  코드오너
- [x]  vscode settings
