### ISSUE TITLE
[feat] 최종 컨펌 QA

### ISSUE THREAD

**Issue by hanseulhee** [GymHubCommunity/GymHub-FE#239]
### 🏋🏻 어떤 개발 사항인가요?

발표 전 페이지 최종 컨펌하면서 안되는 부분을 수정합니다 QA

### 💪🏻 TODO

- [x] 회원 탈퇴 후 로그인 페이지 리다이렉트
- [x] 마이페이지 리펙토링
- [x] 메인페이지 , 마이페이지 게시물 없을 경우 마크업 ,스타일 추가
- [x] 레지스터 페이지 presigndedURL 호출 오류 수정 
- [x] 로그인이 안되였을 경우 로그인 페이지로 리다이렉트
- [x] 메인페이지 게시글 댓글 버튼 추가 
- [x] middleware 무한 리다이렉트 수정
